spring:
  application:
    name: DormHub
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml